### ISSUE TITLE
Add security audit action

### ISSUE THREAD

**Issue by wayofthepie** [wayofthepie/gram#28]
Other repos I have that are rust have a security audit action. For example see the [dockerfile-parser-rs security audit action](https://github.com/wayofthepie/dockerfile-parser-rs/blob/c937124aa3da41dcdc769937debdd2c0659c2f49/.github/workflows/security_audit.yml#L1-L18).

```yaml
name: security audit
on:
  schedule:
    - cron: "0 8 * * *"
  push:
    paths:
      - "Cargo.*"
  pull_request:
    branches:
      - master
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```
